/**
 * Generated by tsnapi — public API snapshot of `trusted-publish`
 */
// #region Interfaces
export interface ClaimsInput {
  repository?: string;
  workflow?: string;
  project?: string;
  file?: string;
  environment?: string;
  orgId?: string;
  projectId?: string;
  pipelineDefinitionId?: string;
  vcsOrigin?: string;
  contextIds?: string[];
}
export interface Config extends ConfigOverride {
  profiles?: Record<string, ConfigOverride>;
}
export interface ConfigOverride extends Omit<Partial<TrustedPublishConfig>, 'discovery'> {
  discovery?: Partial<DiscoveryConfig>;
}
export interface DiscoveryConfig {
  fromWorkspaces: boolean;
  fromGlobs: boolean;
  workspaceGlobs: string[];
  packageJsonGlobs: string[];
}
export interface LoadConfigInput {
  cwd?: string;
  config?: string;
  profile?: string;
  requestTimeoutMs?: number | string;
  provider?: ProviderType;
  package?: string;
  include?: string | string[];
  exclude?: string | string[];
  ignores?: string | string[];
  includePrivate?: boolean;
  workspaceGlobs?: string | string[];
  packageJsonGlobs?: string | string[];
  fromWorkspaces?: boolean;
  fromGlobs?: boolean;
  repository?: string;
  workflow?: string;
  project?: string;
  file?: string;
  environment?: string;
  orgId?: string;
  projectId?: string;
  pipelineDefinitionId?: string;
  vcsOrigin?: string;
  contextIds?: string | string[];
  allowPublish?: boolean;
  allowStagePublish?: boolean;
  permissions?: TrustPermission[];
  concurrency?: number | string;
  failFast?: boolean;
  maxRetries?: number | string;
  retryDelayMs?: number | string;
  maxRetryDelayMs?: number | string;
  rateLimitMs?: number | string;
  dryRun?: boolean;
  json?: boolean;
  silent?: boolean;
  verbose?: boolean;
  yes?: boolean;
  registry?: string;
  token?: string;
  otp?: string;
}
export interface NpmTrustRemoteItem extends TrustConfig {
  id?: string;
}
export interface PackageCommandResult {
  packageName: string;
  packageDir: string;
  status: CommandResultStatus;
  message: string;
  trustId?: string;
}
export interface PackageMeta {
  dir: string;
  manifestPath: string;
  name: string;
  private: boolean;
}
export interface PermissionInput {
  permissions?: string[];
  allowPublish?: boolean;
  allowStagePublish?: boolean;
}
export interface RevokeOptions {
  id: string;
}
export interface RunWithConcurrencyOptions<R, T> {
  failFast?: boolean;
  shouldStop?: (_: R) => boolean;
  onError?: (_: unknown, _: T, _: number) => void;
}
export interface Summary {
  total: number;
  configured: number;
  already: number;
  revoked: number;
  failed: number;
  skipped: number;
}
export interface TargetSelectOptions {
  package?: string;
  include: string[];
  exclude: string[];
  ignores: string[];
  includePrivate: boolean;
}
export interface TrustClaimsCircleCI {
  'oidc.circleci.com/org-id': string;
  'oidc.circleci.com/project-id': string;
  'oidc.circleci.com/pipeline-definition-id': string;
  'oidc.circleci.com/vcs-origin': string;
  'oidc.circleci.com/context-ids'?: string[];
}
export interface TrustClaimsGitHub {
  repository: string;
  workflow_ref: {
    file: string;
  };
  environment?: string;
}
export interface TrustClaimsGitLab {
  project_path: string;
  ci_config_ref_uri: {
    file: string;
  };
  environment?: string;
}
export interface TrustConfig {
  id?: string;
  type: ProviderType;
  claims: TrustClaims;
  permissions?: TrustPermission[];
}
export interface TrustedPublishConfig {
  cwd?: string;
  registry: string;
  requestTimeoutMs: number;
  provider: ProviderType;
  package?: string;
  include: string[];
  exclude: string[];
  ignores: string[];
  includePrivate: boolean;
  discovery: DiscoveryConfig;
  claims: ClaimsInput;
  permissions: TrustPermission[];
  concurrency: number;
  failFast: boolean;
  maxRetries: number;
  retryDelayMs: number;
  maxRetryDelayMs: number;
  rateLimitMs: number;
  dryRun: boolean;
  json: boolean;
  silent: boolean;
  verbose: boolean;
  yes: boolean;
  token?: string;
  otp?: string;
  profile?: string;
}
// #endregion

// #region Types
export type CommandResultStatus = 'configured' | 'already' | 'failed' | 'skipped' | 'revoked';
export type NodeApiConfigInput = LoadConfigInput;
export type NodeApiPackageMeta = PackageMeta;
export type NodeApiRevokeOptions = RevokeOptions;
export type NodeApiRuntimeConfig = TrustedPublishConfig;
export type NodeApiTrustPayload = TrustConfig;
export type ProviderType = 'github' | 'gitlab' | 'circleci';
export type TrustClaims = TrustClaimsGitHub | TrustClaimsGitLab | TrustClaimsCircleCI;
export type TrustPermission = 'createPackage' | 'createStagedPackage';
// #endregion

// #region Classes
export declare class NpmTrustClient {
  private readonly options;
  private mutationQueue;
  private nextMutationAt;
  constructor(_: ClientOptions);
  list(_: string): Promise<NpmTrustRemoteItem[]>;
  setup(_: string, _: TrustConfig): Promise<Response>;
  revoke(_: string, _: string): Promise<Response>;
  private request;
  private requestWithRetry;
  private fetchWithTimeout;
  private waitForRateLimit;
  private isRetryableStatus;
  private getRetryAfterMs;
  private packageUrl;
  private packageTrustIdUrl;
}
// #endregion

// #region Functions
export declare function buildTrustConfig(_: TrustedPublishConfig): TrustConfig;
export declare function buildTrustedPublishPayload(_: NodeApiRuntimeConfig): TrustConfig;
export declare function createReporter(_: TrustedPublishConfig): {
  title(_: string): void;
  info(_: string): void;
  success(_: string): void;
  warn(_: string): void;
  error(_: string): void;
  result(_: PackageCommandResult): void;
  summary(_: Summary, _: PackageCommandResult[]): void;
};
export declare function createTrustedPublishClient(_: TrustedPublishConfig): NpmTrustClient;
export declare function defineConfig<T extends Config>(_: T): T;
export declare function discoverPackages(_: TrustedPublishConfig): Promise<PackageMeta[]>;
export declare function discoverTrustedPublishPackages(_: NodeApiRuntimeConfig): Promise<PackageMeta[]>;
export declare function listTrustedPublish(_: NodeApiRuntimeConfig): Promise<number>;
export declare function loadTrustedPublishConfig(_: LoadConfigInput): Promise<TrustedPublishConfig>;
export declare function mergeConfig(_: TrustedPublishConfig, _: ConfigOverride): TrustedPublishConfig;
export declare function normalizeRegistry(_: string): string;
export declare function parsePermissions(_: PermissionInput): TrustPermission[];
export declare function resolveCwd(_?: string): string;
export declare function resolveTrustedPublishConfig(_: NodeApiConfigInput): Promise<TrustedPublishConfig>;
export declare function revokeTrustedPublish(_: NodeApiRuntimeConfig, _: NodeApiRevokeOptions): Promise<number>;
export declare function runList(_: TrustedPublishConfig): Promise<number>;
export declare function runRevoke(_: TrustedPublishConfig, _: RevokeOptions): Promise<number>;
export declare function runSetup(_: TrustedPublishConfig): Promise<number>;
export declare function runVerify(_: TrustedPublishConfig): Promise<number>;
export declare function runWithConcurrency<T, R>(_: T[], _: number, _: (_: T, _: number) => Promise<R>, _?: RunWithConcurrencyOptions<R, T>): Promise<R[]>;
export declare function setupTrustedPublish(_: NodeApiRuntimeConfig): Promise<number>;
export declare function sleep(_: number): Promise<void>;
export declare function summarize(_: PackageCommandResult[]): Summary;
export declare function toArray(_: string | string[] | undefined): string[];
export declare function uniq<T>(_: T[]): T[];
export declare function validateConfig(_: TrustedPublishConfig): void;
export declare function verifyTrustedPublish(_: NodeApiRuntimeConfig): Promise<number>;
// #endregion

// #region Variables
export declare const CONFIG_FILES: string[];
export declare const DEFAULT_CONFIG: TrustedPublishConfig;
export declare const DEFAULT_IGNORES: string[];
// #endregion