import type { CAC } from 'cac'

export function configureCliOptions(cli: CAC, version: string): CAC {
  return cli
    .version(version)
    .option('--cwd <path>', 'working directory')
    .option('--config <path>', 'custom config file')
    .option('--profile <name>', 'config profile')
    .option('--provider <type>', 'provider: github|gitlab|circleci')
    .option('--package <name>', 'single package name')
    .option('--include <names>', 'comma-separated package names')
    .option('--exclude <names>', 'comma-separated package names')
    .option('--ignores <globs>', 'comma-separated ignore globs')
    .option('--workspace-globs <globs>', 'additional workspace globs')
    .option('--package-json-globs <globs>', 'package.json search globs')
    .option('--from-workspaces', 'enable workspace discovery')
    .option('--from-globs', 'enable glob discovery')
    .option('--include-private', 'include private packages')
    .option('--repository <value>', 'github repository owner/repo')
    .option('--workflow <file>', 'github workflow file')
    .option('--project <value>', 'gitlab project path')
    .option('--file <file>', 'provider file (gitlab/github)')
    .option('--environment <name>', 'CI environment')
    .option('--org-id <id>', 'circleci org id')
    .option('--project-id <id>', 'circleci project id')
    .option('--pipeline-definition-id <id>', 'circleci pipeline definition id')
    .option('--vcs-origin <value>', 'circleci vcs origin provider/owner/repo')
    .option('--context-ids <ids>', 'circleci context ids (comma separated)')
    .option('--allow-publish', 'allow publish (createPackage)')
    .option(
      '--allow-stage-publish',
      'allow stage publish (createStagedPackage)',
    )
    .option('--concurrency <n>', 'parallelism')
    .option('--fail-fast', 'stop processing after first failed package')
    .option('--max-retries <n>', 'max retry times on 429/5xx')
    .option('--retry-delay-ms <n>', 'base retry delay in ms')
    .option('--max-retry-delay-ms <n>', 'max retry delay in ms')
    .option('--rate-limit-ms <n>', 'minimum interval between mutation requests')
    .option('--request-timeout-ms <n>', 'request timeout in milliseconds')
    .option('--dry-run', 'preview only')
    .option('--json', 'json output')
    .option('--silent', 'silent logs')
    .option('--verbose', 'verbose logs')
    .option('--yes', 'skip confirmation')
    .option('--registry <url>', 'npm registry')
    .option('--token <token>', 'npm token')
    .option('--otp <otp>', 'npm 2fa otp')
}
